=head1 The Pegex Manual

Welcome to Pegex, the Acmeist Parser technology.

This manual is basically an index to other useful Pegex documents.

=over

=item L<Pegex::Syntax>

Describes all the components of the Pegex syntax.

=item L<Pegex::API>

Documents the various Pegex classes and interfaces.

=item L<Pegex::Example::JSON>

A complete example of writing a JSON parser with Pegex.

=back
