=encoding utf8

=head1 Pegex Tutorials

Pegex has a growing number of tutorials on how to do various parsing tasks.

This document is just an index to the current tutorials.

=over

=item L<Pegex::Tutorial::JSON>

This is a very in-depth tutorial of the creation of the module L<Pegex::JSON>
(a JSON decoder that uses Pegex) and the thought that went into creating it.
It covers almost all of the L<Pegex::Syntax> as well.

=item L<Pegex::Tutorial::Calculator>

Pegex comes with an C<examples/> directory. One example is
L<Pegex/examples/calculator.pl>. It's a simple precedence parser (and
evaluator) for arithmetic expressions like this one:

   1 * (2 + 3) / (4 ^ 5 ^ 6 - -7)

=back

=head1 See Also

=over

=item L<Pegex::API>

How to use the various Pegex modules and functions.

=item L<Pegex::Syntax>

A detailed description of the Pegex grammar language syntax.

=item L<Pegex::Resources>

A list of all things Pegex.

=back
